version: '3.8'

services:
  omp-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
    volumes:
      # Mount source code for development (hot reload)
      - ./src:/app/src:ro
    ports:
      - "5087:8080"  # Map to the development port from README

  postgres:
    ports:
      - "5433:5432"  # Use different port to avoid conflicts with local PostgreSQL
    environment:
      POSTGRES_DB: ompDB_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
    driver: local
